apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: vulnerable-app:latest  # ⚠️ latest tag
        ports:
        - containerPort: 8080
        env:
        - name: JWT_SECRET
          value: "plainsecret"        # ⚠️ hardcode
