apiVersion: v1    # ⚠️ ingress/egress no restrict
kind: Service
metadata:
  name: db
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: postgres:9.6         # ⚠️ CVE Version
        env:
        - name: POSTGRES_PASSWORD
          value: "123456"           # ⚠️ Hardcode & Weak Password
